controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_camera_controller:
      type: position_controllers/JointGroupPositionController

    joint_camera_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_camera_controller:
  ros__parameters:
    joints:
      - base_USBcamera_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity