controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    arm_joint_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    camera_joint_controller:
      type: position_controllers/JointGroupPositionController

arm_joint_controller:
  ros__parameters:
    joints:
      - base_arm1_joint
      - arm1_arm2_joint
      - arm2_arm3_joint
    command_interfaces:
      - velocity

camera_joint_controller:
  ros__parameters:
    joints:
      - base_camera_low_joint
    command_interface:
      - position